add validation
subquery/indexer-ssl-proxy pull request #2
Opened 2023-05-22 00:43 UTC by Jianzhuo

2023-05-22 22:40 UTC, ianhe8x requested changes

2023-05-22 22:40 UTC, ianhe8x commented on src/index.ts
> +import { useGetIndexerQuery } from '@subql/react-hooks';
You should use `GraphqlQueryClient.getIndexer` from `@subql/network-clients`
since this is not a react project, better don't introduce react dependencies

2023-05-22 22:42 UTC, ianhe8x commented on src/index.ts
> +  if(!indexers.get(indexer)){
what if indexer changes their url?

2023-05-23 22:28 UTC, HZHAIX commented
@Jianzhuo

- [ ] Check whether the proxy endpoint is hosted by the indexer, you can send GET request to `${proxyEndpoint}/healthy` and get the indexerAddress from the response. 
- [ ] Use node cache do the mem cache
- [ ] For each query, compare the  `proxyEndpoint` with the the `url` in the cache, if they are not same, make sure the incoming `proxyEndpoint` is the new one and update the cache url. Reject the query if the proxyEndpoint is not consistent.

2023-05-24 07:19 UTC, ianhe8x approved these changes

2023-05-24 07:19 UTC, merged